version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - npm install -g aws-cdk
  pre_build:
    commands:
    - echo In the pre_build phase...
    - cdk ls
  build:
    commands:
    - echo Build started on `date`
    - cdk bootstrap
    - cdk deploy --require-approval never
  post_build:
    commands:
    - echo Build completed on `date`
